source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/brightcove/BrightcoveSpecs.git'

platform :ios, '9.0'

target 'IMATest' do

use_frameworks!

#pod 'Brightcove-Player-Core'
pod 'Brightcove-Player-IMA', '~>6.2.2'
pod 'GoogleAds-IMA-iOS-SDK', '~>3.6'


  target 'IMATestTests' do
    inherit! :search_paths
  end

  target 'IMATestUITests' do
    inherit! :search_paths
  end

end
