# Uncomment the next line to define a global platform for your project
source 'https://github.com/brightcove/BrightcoveSpecs.git'
platform :ios, '9.0'

target 'CocoapodsTest' do
# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!
pod 'Brightcove-Player-Core'  

# Pods for CocoapodsTest

  target 'CocoapodsTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CocoapodsTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
